### ISSUE TITLE
Error 403 Checkout

### ISSUE THREAD

**Issue by tknologyk** [mercadopago/cart-oscommerce#12]
Hello!

I have an error 403 when I checkout and my URL go to http://www.puchale.mx/mercadopago.php?bt=http://www.mercadopago.com/mlm/checkout/pay?pref_id=18037671-33238087-3536-433f-95f6-2bbd800d1ba8

Anyone have idea how i can resolve it? 

thank you :)

**Comment by sebagun** [comment]
I cannot see the product page on that URL, maybe is an issue on your server, but the MP checkout page is fine if you access it directly:

http://www.mercadopago.com/mlm/checkout/pay?pref_id=18037671-33238087-3536-433f-95f6-2bbd800d1ba8

Regards
